#!/usr/bin/env python3
"""Emit the catalogue reconstructed by r147/src/catalogue147.py as a C header,
so the second chain implementation never computes its own geometry: it consumes
the INDEPENDENT (string-algebra) reconstruction that was shown field-by-field
equal to the first implementation's internal tables."""
from __future__ import annotations
import sys
from pathlib import Path

R147 = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(R147 / "src"))
import catalogue147 as C                                            # noqa: E402


def arr(name, vals, typ="int"):
    body = ",".join(str(v) for v in vals)
    return f"static const {typ} {name}[] = {{{body}}};\n"


def main():
    free, dA, dB, paid, kind, heavy = C.catalogue()
    n = C.N
    out = ["/* generated by r147/src/genheader147.py -- do not edit */\n",
           f"#define NW2 {n}\n#define NQ2 144\n#define NH2 120\n"]
    out.append(arr("HEX2", C.HEX))
    out.append(arr("ORB2", C.ORB))
    out.append(arr("PH2", C.PHASE))
    out.append(arr("FREE2", free))
    out.append(arr("DA2", dA))
    out.append(arr("DB2", dB))
    flat, off = [], [0]
    for v in range(n):
        flat += paid[v]
        off.append(len(flat))
    out.append(arr("PAID2", flat))
    hflat, hcost, hoff = [], [], [0]
    for v in range(n):
        for t, c in heavy[v]:
            hflat.append(t)
            hcost.append(c)
        hoff.append(len(hflat))
    out.append(arr("HV2", hflat))
    out.append(arr("HVC2", hcost, "unsigned char"))
    out.append(arr("HVOFF2", hoff))
    p = R147 / "src" / "catalogue147.h"
    p.write_text("".join(out))
    print(f"wrote {p}: {n} words, paid {len(flat)}, heavy {len(hflat)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
