#!/usr/bin/env python3
"""Fragment debt: definition, computation over the 24 RA2 states, and a
computational test of both (a) a proven sub-lemma about post-abandonment
joints, and (b) why the naively-requested scalar debt potential fails.

Definitions used (all derived directly from exact.f1_normal_form /
exact.extend, not invented ad hoc):

  fragment repair: any joint (weight-2/3 move) whose TARGET permutation
  lies inside the current fragment_hex. Only a joint can do this --
  weight-1 rotation only ever moves within the CURRENT hex.

  d_frag(S) = 6 - popcount(hex_masks[fragment_hex]) if fragment_hex is not
  None, else 0. This is exactly the number of windows still missing from
  the fragment hexagon.

Proven sub-lemma (verified below against the real engine, not just
symbolically): once F=1 (the walk's one allowed abandonment has fired),
EVERY subsequent joint must have abandonment=False. This follows directly
from extend()'s abandonment formula (abandonment = "the rotation successor
of the pre-joint p is not yet visited") together with TARGET_F=1: any
transition with abandonment=True while F is already 1 would need
delta_F=1, pushing F to 2, which area_a_prune_reason rejects
("F_exceeded"). So after F=1, a hex can only ever be left at a
rotation-collision boundary (never voluntarily early).

Naive claim tested and REFUTED: "d_frag(S) > 0 implies the walk cannot
complete." This is not a real obstruction -- d_frag(S) > 0 merely restates
"this hexagon still has an unvisited window", which is true of every
not-yet-full hexagon in every unfinished walk, fragment or not. It carries
no more information than "722 - visited_count > 0" until it is combined
with a REACHABILITY argument (can some future joint actually target the
missing window(s)?), which a scalar potential cannot express. A minimal
abstract counter-model is documented in research/FRAGMENT_DEBT_LEMMA.md.
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path
from typing import Any, Dict, List

ROOT = Path(__file__).resolve().parent.parent
WORK = ROOT / "legacy_research" / "work"


def _load(name: str, filename: str):
    path = WORK / filename
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {path}")
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


macro = _load("vfd_macro", "superperm_partial_f1_macro.py")
exact = macro.exact


def d_frag(state: "exact.ExactState") -> int:
    form = exact.f1_normal_form(state)
    if form is None or form.fragment_hex is None:
        return 0
    return 6 - bin(state.hex_masks[form.fragment_hex]).count("1")


def verify_post_f1_blocked_only(states: List["exact.ExactState"], depth: int, edge_cap: int) -> Dict[str, Any]:
    """BFS from each F=1 state and confirm every LEGAL (area_a_prune_reason
    is None) reachable joint has abandonment=False (the proven sub-lemma),
    over the real engine.

    macro_edges() itself returns the raw structural transition graph and
    does NOT enforce F<=1 -- a move with abandonment=True from an F=1 state
    is structurally generated (its target state has F=2) but is then
    filtered out by area_a_prune_reason's "F_exceeded" check, exactly like
    any other illegal continuation. Those pruned edges are not walk steps
    a legal continuation could ever take, so they must be excluded before
    counting a "violation" of the sub-lemma -- counting them would conflate
    "structurally generated by macro_edges" with "legal in Area A"."""
    from collections import deque
    checked = 0
    violations = 0
    violation_examples = []
    for seed in states:
        assert seed.F == 1, "sub-lemma only applies once F=1"
        frontier = deque([(0, seed)])
        edges = 0
        while frontier and edges < edge_cap:
            d, s = frontier.popleft()
            if d >= depth:
                continue
            for e in macro.macro_edges(s):
                edges += 1
                reason = macro.area_a_prune_reason(e.joint.state, macro.AREA_A)
                if reason is not None:
                    continue  # illegal continuation -- not a real walk step, excluded
                checked += 1
                if e.joint.abandonment:
                    violations += 1
                    if len(violation_examples) < 3:
                        violation_examples.append({"label": e.label, "resulting_F": e.joint.state.F})
                frontier.append((d + 1, e.joint.state))
                if edges >= edge_cap:
                    break
    return {
        "legal_transitions_checked": checked,
        "abandonment_after_f1_found_among_legal": violations,
        "violation_examples": violation_examples,
        "sublemma_holds": violations == 0,
    }


def naive_claim_correlation(records: List[Dict[str, Any]]) -> Dict[str, Any]:
    """d_frag at the post-A2 (F=1) state, cross-tabulated against the
    already-established capacity-failure status, purely as an honest
    observational check -- NOT claimed as a proof either way."""
    from collections import Counter
    table = Counter((r["d_frag_after_A2"], r["status"]) for r in records)
    return {"d_frag_after_A2_vs_status": {str(k): v for k, v in table.items()}}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ledger", default=str(ROOT / "outputs" / "u_branch_state_ledger.json"))
    parser.add_argument("--ra2-exact-analysis", default=str(ROOT / "outputs" / "ra2_exact_analysis.json"))
    parser.add_argument("--sublemma-depth", type=int, default=6)
    parser.add_argument("--sublemma-edge-cap", type=int, default=20000)
    parser.add_argument("--output", default=str(ROOT / "outputs" / "ra2_fragment_debt.json"))
    args = parser.parse_args()

    ledger = json.loads(Path(args.ledger).read_text(encoding="utf-8"))
    ra2 = ledger["words"]["RA2"]
    status_by_hash = {r["target_hash"]: r["status"] for r in json.loads(Path(args.ra2_exact_analysis).read_text())["results"]}

    records = []
    states_f1 = []
    for w in ra2["witnesses"]:
        state = exact.state_from_json(w["final_state_json"])
        states_f1.append(state)
        records.append({
            "target_hash": w["target_hash"],
            "status": status_by_hash[w["target_hash"]],
            "d_frag_after_A2": d_frag(state),
        })

    sublemma = verify_post_f1_blocked_only(states_f1, args.sublemma_depth, args.sublemma_edge_cap)
    correlation = naive_claim_correlation(records)

    report = {
        "schema": "ra2-fragment-debt-v1",
        "definition": "d_frag(S) = 6 - popcount(hex_masks[fragment_hex]) if fragment_hex exists else 0",
        "proven_sublemma_post_f1_blocked_only": sublemma,
        "naive_scalar_claim": {
            "claim": "d_frag(S) > 0 implies walk cannot complete",
            "status": "REFUTED as a general principle -- see research/FRAGMENT_DEBT_LEMMA.md for the minimal abstract counter-model",
            "reason": (
                "d_frag(S) > 0 merely restates that the fragment hex has an "
                "unvisited window, true of every not-yet-full hex in every "
                "unfinished state; it is not a reachability statement, so no "
                "monotone scalar built only from it can be safe without "
                "additional positional/reachability information."
            ),
        },
        "records": records,
        "observational_correlation_not_a_proof": correlation,
    }
    Path(args.output).write_text(json.dumps(report, indent=2, sort_keys=True, default=str), encoding="utf-8")
    print(json.dumps({
        "wrote": args.output,
        "sublemma_holds": sublemma["sublemma_holds"],
        "d_frag_values": [r["d_frag_after_A2"] for r in records],
    }, indent=2))


if __name__ == "__main__":
    main()
